export enum MoviesActionType {
  FETCH_MOVIES = "FETCH_MOVIES",
  FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_MORE_SUCCESS = "FETCH_MOVIES_MORE_SUCCESS",
  FETCH_MOVIES_FAIL = "FETCH_MOVIES_FAIL",
  SET_SEARCH_INPUT = "SET_SEARCH_INPUT",
  SET_SEARCH_BY = "SET_SEARCH_BY",
  SET_SORT_BY = "SET_SORT_BY",
}
